repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the ref you want to point at
    hooks:
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args:
          - --autofix
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@open-turo/commitlint-config-conventional"]
  # - repo: https://github.com/rhysd/actionlint
    # rev: v1.6.9
    # hooks:
      # - id: actionlint
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 2.1.6 # or specific git tag
  #   hooks:
  #     - id: shellcheck
  #     - id: shfmt
  - repo: local
    hooks:
      - id: swiftformat
        name: swiftformat
        entry: Scripts/run_swiftformat
        language: system
